from django.urls import path, include
from . import views

urlpatterns = [
    path('form/inquiry', views.inquiry_form_view, name='inquiry_form_view'),
    path('form/supplier', views.supplier_form_view, name='supplier_form_view'),
    path('form/quotation', views.quotation_form_view, name='quotation_form_view'),
    path('form/technical-offer', views.technicalOffer_form_view, name='technical_form_view'),
    path('form/request', views.request_form_view, name='request_form_view'),
    path('form/purchase-order', views.purchaseOrder_form_view, name='purchaseOrder_form_view'),
    path('form/forwarder', views.forwarder_form_view, name='forwarder_form_view'),
    path('form/commercial-offer', views.commercialOffer_form_view, name='commercialOffer_form_view'),
    path('form/shipping', views.shipping_form_view, name='shipping_form_view'),
    path('form/order-registration', views.orderRegistration_form_view, name='orderRegistration_form_view'),
    path('form/custom-clearance', views.customClearance_form_view, name='customClearance_form_view'),
    path('form/expert', views.expert_form_view, name='expert_form_view'),
    path('form/customer', views.customer_form_view, name='customer_form_view'),
    path('form/bank-gurantee', views.bankGuarantee_form_view, name='bankGuarantee_form_view'),
    path('form/financial-report-foreign/', views.financialReportForeign_form_view, name='financialReportForeign_form'),
    path('form/financial-report-irr/', views.financialReportIRR_form_view, name='financialReportIRR_form'),
    path('form/advance-payment-supplier/', views.advancePaymentSupplier_form_view, name='advancePaymentSupplier_form'),
    path('form/balance-payment-supplier/', views.balancePaymentSupplier_form_view, name='balancePaymentSupplier_form'),
    path('form/forwarder-payment/', views.forwarderPayment_form_view, name='forwarderPayment_form'),
    path('form/closed/', views.closed_form_view, name='closedForm_form'),

    path('search/inquiry', views.inquiry_search, name='inquiry_search'),
    path('search/supplier', views.supplier_search, name='supplier_search'),
    path('search/quotation', views.quotation_search, name='quotation_search'),
    path('search/technical-offer', views.technicalOffer_search, name='technicalOffer_search'),
    path('search/request', views.request_search, name='request_search'),
    path('search/purchase-order', views.purchaseOrder_search, name='purchaseOrder_search'),
    path('search/forwarder', views.forwarder_search, name='forwarder_search'),
    path('search/commercial-offer', views.commercialOffer_search, name='commercialOffer_search'),
    path('search/shipping', views.shipping_search, name='shipping_search'),
    path('search/order-registration', views.orderRegistration_search, name='orderRegistration_search'),
    path('search/custom-clearance', views.customClearance_search, name='customClearance_search'),
    path('search/expert', views.expert_search, name='expert_search'),
    path('search/customer', views.customer_search, name='customer_search'),
    path('search/bank-gurantee', views.bankGuarantee_search, name='bankGuarantee_search'),
    path('search/financial-report-foreign', views.financialReportForeign_search, name='financialReportForeign_search'),
    path('search/financial-report-irr', views.financialReportIRR_search, name='financialReportIRR_search'),
    path('search/advance-payment-supplier', views.advancePaymentSupplier_search, name='advancePaymentSupplier_search'),
    path('search/balance-payment-supplier', views.balancePaymentSupplier_search, name='balancePaymentSupplier_search'),
    path('search/forwarder-payment', views.forwarderPayment_search, name='forwarderPayment_search'),
    path('search/closed', views.closed_search, name='closed_search'),

    path('', views.home, name='home'),
]
