# Generated by Django 4.2.4 on 2023-08-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='mob_number',
        ),
        migrations.AlterField(
            model_name='expert',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
