# Generated by Django 4.2.3 on 2023-08-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialoffer',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='technicaloffer',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
