# Generated by Django 4.2.4 on 2024-03-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='date',
            new_name='inquiry_date',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='deadline',
            new_name='to_date',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='co_date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='po_date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='to_date',
            field=models.DateField(null=True, blank=True),
        ),
    ]
