# Generated by Django 4.2.4 on 2023-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_expert_mob_number_alter_expert_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderregistration',
            name='inquiry_1',
        ),
        migrations.AddField(
            model_name='orderregistration',
            name='inquiries',
            field=models.ManyToManyField(related_name='order_registrations', to='form.inquiry'),
        ),
    ]
